### ISSUE TITLE
Canon PTZ Development Input and Testing

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-canon-ptz#1]
Hey all, 

I'm interested to get in touch with devs who are working on this Canon PTZ module. 

I own two Canon CR N300s and am currently using them with a mix of the Sony VISCA, Panasonic, and Lumens modules. 

Happy to test and provide feedback. 

Thanks, David

**Comment by josephdadams** [comment]
I’m currently finishing this up with Canon but once they are happy with it I’ll release it into the beta builds and you can try it out! Works pretty great with the CR N300 they sent me to demo with.

**Comment by davidjoshuaford** [comment]
Thanks Joseph, look forward to checking it out!

**Comment by LYMPIA** [comment]
Awesome !  I also look foward to checking it out too ! We've been using multiple CR-n500 and CR-N300 since july. These are some incredible remote camera.

**Comment by josephdadams** [comment]
This is in the beta builds now, so please go check it out and file a new issue here if something isn't working right.

**Comment by davidjoshuaford** [comment]
Will do, thank you!

**Comment by LYMPIA** [comment]
Nice ! Thank You. Will test this next week :)
