### ISSUE TITLE
Last Used Feedback not showing up

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-canon-ptz#10]
The dropdown menu for the "Last Used Feedback" does not present any options. 

<img width="674" alt="ptz" src="https://user-images.githubusercontent.com/76959770/155425562-0e4d4f7f-ede5-452e-a84d-42b37501e237.png">

Same for the Focus Speed Setting. Also:
  - Can Focus Speed setting be referred to as Low, Med, High rather than 0, 1, 2?
  - Could we please have a Focus Speed Toggle action, that cycles through the Low, Med, High?
  - Lastly, is it possible to get the focal length readout in the variable feedback? 
 
<img width="697" alt="focus speed" src="https://user-images.githubusercontent.com/76959770/155433102-abcb9aaf-3488-4d1b-bcd7-114453fa95f2.png">
 
Thank you for your work!

**Comment by josephdadams** [comment]
I can try to fix these. I no longer have access to the camera so it’s not possible to test.

**Comment by josephdadams** [comment]
I believe I have all of this sorted for you now. I'll push it out and you can check it.

**Comment by davidjoshuaford** [comment]
Feedback for Last Recall Preset is now working!

The one that is not is the Action "Lens - Set Focus Speed"


![focus speed](https://user-images.githubusercontent.com/76959770/155631476-196d68ab-f33a-419b-9719-3fc70b3f3df2.jpg)

Is it possible to have an action to set the Lens Focal distance to a numeral millimeter?

**Comment by josephdadams** [comment]
Pushing a fix for the set focus speed.

I'm not sure if it's possible to set that value or not. Do you know the value range from min to max?

You should be able to test it by going to `http://192.168.1.5/-wvhttp-01-/control.cgi?c.1.focus.length=value`

Joseph

**Comment by josephdadams** [comment]
Did you try the latest fix - and were you able to test the focal distance paramter?

**Comment by davidjoshuaford** [comment]
I'm testing build 3976 right now - "Lens - Set Focus Speed" dropdown menu is working correctly :) 

In the variable feedback for focus, it seems Near is 2048, and Far is 987. 

I've tested my particular camera at http://192.168.8.101/-wvhttp-01-/control.cgi?c.1.focus.length=value

it returns: 

--- WebView Livescope Http Server Error ---
Parameter Missing
1 parameter(s)

**Comment by josephdadams** [comment]
Just confirming that you used something like: 
http://192.168.8.101/-wvhttp-01-/control.cgi?c.1.focus.length=987 (where you replaced `value` with `987`. I know it's dumb but I have to ask. If so, then it probably just doesn't support setting this property this way.

**Comment by davidjoshuaford** [comment]
Good question - I have tried adding in 987, as well as the value readout from the Variable (ie, currently the module variable feedback says the focal value is 1456), but it still gives me the same error: 

--- WebView Livescope Http Server Error ---
Parameter Missing
1 parameter(s)

Do you know what those numbers refer to? I'm guessing not mm since they appear inverted from near to far.

**Comment by josephdadams** [comment]
I have no idea. It's just what is returned by that property. It could just be something internal used on the web interface.

**Comment by josephdadams** [comment]
I messaged you on Slack - just making sure you saw it.
