### ISSUE TITLE
Exposure Compensation

### ISSUE THREAD

**Issue by apochroma** [bitfocus/companion-module-canon-ptz#12]
According to the Canon_XC_Control_Protocol_Specifications and to my practical use of the cameras, I am missing these Button-Set:
Exposure Compensation or so called Light Amount Correction Information on page 107 c..ae.brightness.list :=
This would be very useful. Because if you set to Full Auto, sometimes the background is to dark or opposite to bright, the important person which should be correct balanced won't be correct. So you can still use automatic mode but tell the camera to get a brighter or darker image. Ex.

Would love to have this implemented! Thanks a lot.

Kind regards
Claus
PS: Sorry, i accidentaly closed the first poll...

**Comment by josephdadams** [comment]
Can you send me whatever manual you are referring to?

**Comment by apochroma** [comment]
I can't find the origin anymore, but i packed it into my repository.
https://github.com/apochroma/ptz-ps4-crn300

**Comment by josephdadams** [comment]
This?

c.1.ae.brightness:=0
c.1.ae.brightness.min:=-8
c.1.ae.brightness.max:=8
c.1.ae.brightness.list:=-8,-6,-4,-2,0,2,4,6,8

**Comment by josephdadams** [comment]
Ok, I added ae gain limit, brightness, photometry, flicker reduct, and resp actions and variables to the module and pushed this to the betas. I hope this is a blessing to you. Have a nice day.

**Comment by josephdadams** [comment]
You'll need to update to the latest beta build to get it.

**Comment by apochroma** [comment]
> You'll need to update to the latest beta build to get it.

I'm not quite sure how to update. But i manually copied your latest files in to my raspberry pi and figured out how to add a regular button with the appropriate tasks.
Probablay for your interest, the values in range -8 to +8 can also have steps in between. Not only  -8, -6, -4 and so on. That is not written in the documentation, but I have another device from Skaarhoj (PTZ Pro) where it is actually programmed.

0 equals No Compensation
1 equals +0.25 EV (exposure value)
2 equals +0.5 EV (exposure value)
3 equals +0.75 EV (exposure value)
4 equals +1.0 EV (exposure value)
and so on (also in the opposite direction: minus)

Thank you again very much for adding this more than valueable feature. Especially when people stand before a white or dark wall, this feature is a lifesaver, because the calculated exposure values are the inadequate.
I will also test the other features you implemented... but my next job is so soon, that i will prep first for this job :)
