### ISSUE TITLE
Canon Canon CR-X300

### ISSUE THREAD

**Issue by MandyDroid** [bitfocus/companion-module-canon-ptz#17]
I have setup a Canon CR-X300 control via the Companion software with the Canon PTZ Module. I did use the "Other Cameras" option. In the system log I keep getting the following line every 5 seconds. 

> instance(Camera1): New model detected, reloading module: Canon CR-X300

When I tried to use the auto-detect method I get the following error 5 times every 5 seconds. 

> instance(Camera1): Error parsing response from PTZ: TypeError: Cannot read property 'series' of undefined

It does seem to me that the Other Cameras option does work clean just that repeating line is annoying in the log. Any ideas or suggestions?

Thank You all for your hard work. It is greatly appreciated.

**Comment by josephdadams** [comment]
So it works fine, just annoying logs?

**Comment by MandyDroid** [comment]
I think it works fine. I am kind of looking for some feedback if a notice every 5 seconds would be considered ok? Or normal in Thai setup. On Mar 10, 2023, at 2:34 PM, Joseph Adams ***@***.***> wrote:﻿
So it works fine, just annoying logs?

**Comment by josephdadams** [comment]
I added the CR-X300 as a model in the list.
