### ISSUE TITLE
Canon XC Protocol for C70, C300 Mkiii, C500 Mkii

### ISSUE THREAD

**Issue by mlcook19** [bitfocus/companion-module-canon-ptz#2]
Hey, I have seen that people have had luck with the Canon XF Line of cameras, however that module doesn't work with the cinema line of cameras where they have recently added the XC protocol.

I would be happy to help with the development in any way that I can, however I am not experienced enough to develop this on my own.

Here are links to documentation:

[CameraControlAPI_Reference_v110b_EN.pdf](https://github.com/bitfocus/companion-module-requests/files/5495836/CameraControlAPI_Reference_v110b_EN.pdf)

[CameraControlAPI_OperationGuide_EN.pdf](https://github.com/bitfocus/companion-module-requests/files/5495834/CameraControlAPI_OperationGuide_EN.pdf)

**Comment by josephdadams** [comment]
This new canon-ptz module uses the XC protocol. Can you try it out and see how it fares with your devices?
