### ISSUE TITLE
feedback issue

### ISSUE THREAD

**Issue by Rik83** [bitfocus/companion-module-canon-ptz#23]
actions are ok
variables are ok
but feedback is wrong :
in the dropdown list I have : canon-500: undefined
in the browser I have : No feedbacks match the search
[3.0.0-rc1 (3.0.0-rc1+5909-v3-0.0-rc1-725c3583)](https://bitfocus.io/companion/)

**Comment by Rik83** [comment]
Also 
all the variables $(canon-500:presetname_XX)  are $NA
the $(canon-500:presetLastUsed) is never updated

**Comment by davidjoshuaford** [comment]
In 2.0.4, feedback names are back - great!

However, some feedback states don't work though: 
- the “last used preset” 
- “normal/time/speed mode”

And some of the feedback doesn’t seem to show correctly - for instance, the Show Power state is correct in showing Idle, but not in showing Standby.

**Comment by josephdadams** [comment]
should be fixed now
