### ISSUE TITLE
Selected Preset Feedback

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-canon-ptz#3]
Great work on the PTZ module already - love the thoroughness of the variables and feedback states. 

Is it possible to include feedback for the recalled preset? Ie, if you have a bank of 10 presets, you’d be able to see at a glance camera X is sitting on Y position. This would help when operating multiple cameras. 

Thanks for your work!

**Comment by josephdadams** [comment]
I only have access to this camera for a few more days (Canon sent it to me for development) but it does look like the property `p:=1` is in the info when on preset 1, for example. However, if you move the camera manually after recalling a preset, that doesn't change. So, we could track it like "last preset used", but can't necessarily guarantee that it would still be in that position.

Your thoughts about that?

**Comment by davidjoshuaford** [comment]
I think that would still be valuable. I've had camera assistants chasing 3 or 4 cameras and it would give them a visual cue when they flick back over to a camera to see at a glance at what position they are in (assuming they're not making further manual adjustments after recalling as you mention). I'm guessing there's no way to cancel out the feedback if any manual adjustment is made? Would that have to happen on the Canon side of things? 

Also - I notice you have Preview Tally feedback in there – does the N300 have a green tally lamp? I've only been able to find the red one in the native IP interface. Do you have future use case for Preview Tally, or is that an N500 thing?

**Comment by davidjoshuaford** [comment]
One more thing (sorry for the jump around, just while it's top of mind!) – is it possible to add a Toggle power ON/OFF? I can think of instances where a single push to toggle would help reduce number of button real estate rather than having separate buttons for ON and OFF, and would avoid having to use the latch function. On that note, I don't seem to be getting feedback for the Standby vs Idle?

**Comment by josephdadams** [comment]
The problem with canceling out the feedback is that the module can poll the camera on an interval for the latest data (and it really should, for the best use of the module), and any time it polls, it will receive that (potentially incorrect) value again. So canceling it out would not be effective except between update cycles.

**Comment by davidjoshuaford** [comment]
Ok, you'll know much better than me... Is it possible to implement the last Preset feedback scenario?

**Comment by josephdadams** [comment]
Yes, I've already coded it, testing it here in a few minutes.

Also coded the power toggle.

**Comment by josephdadams** [comment]
And I did find a bug related to the power state feedback, so I think that will work on the next version I push.

**Comment by davidjoshuaford** [comment]
Amazing! will check that out. 

Is there a way to automate the green preview tally into the module instance settings? I can see how to do that using Triggers, but takes a bit of back and forth if changing inputs (ie the module turns on the tally when switching to program, but doesn't alternate red/green when cutting between program/preview). Perhaps a Toggle between Program and Preview would help here, as having only the four ON PGM/ OFF PGM/ ON PVW/ OFF PVW forces the tally to be on or off. Ideally the tally in the module's instance would account for when a camera is utilized in a Key or Supersource...though I appreciate that this becomes a much bigger matrix!

**Comment by davidjoshuaford** [comment]
Any chance of implementing a "White Balance Calibration" command (ie to lock a custom WB while in the A or B modes?)

**Comment by josephdadams** [comment]
I think that tally logic depends on the other modules or programs determining the tally. But I can add a toggle between pvw and pgm lights on the camera. I can't see the front of the camera right now, it's offsite. So we will have to do some testing here to see if sending the preview tally on command automatically turns off the red, or if we also have to send a red off first.

**Comment by josephdadams** [comment]
pvw/pgm tally toggle added. will need your help testing.

white balance calibration with dropdown of a, b added.

**Comment by josephdadams** [comment]
It looks like if you have the camera in `manual` wb for example and run the wb calibrate on `a` for example, it will switch to A mode and then run that. just fyi.

**Comment by josephdadams** [comment]
Ok, I've added these to the repo. If you're running your own dev version, just clone this to the `module-local-dev` folder. Otherwise I'll add it to the beta builds later and ping you when that's done.

**Comment by davidjoshuaford** [comment]
Thanks Joseph, nice work on this!

**Comment by josephdadams** [comment]
@davidjoshuaford it's in the latest betas now too. Building now.
