### ISSUE TITLE
Up Left-Pan/Tilt Broken

### ISSUE THREAD

**Issue by mattssd** [bitfocus/companion-module-canon-ptz#36]
The function of the button is broken. It doesn't respond and says "Undefined"
<img width="441" alt="Screenshot 2024-02-21 at 1 53 07 PM" src="https://github.com/bitfocus/companion-module-canon-ptz/assets/160778381/56569402-4c24-4f12-829f-327ec400e481">

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-canon-ptz/blob/ee20d68927592bae78ac3cf913375fc085266236/src/presets.js#L574

Here be the issue

**Comment by josephdadams** [comment]
fixed in `v2.1.2`
