### ISSUE TITLE
Power toggle

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-canon-ptz#5]
Hi Joseph, it appears that the toggle power function is turning the camera off, but does not turn it back on. The Turn On Power command functions correctly.

**Comment by josephdadams** [comment]
Sorry about that. I couldn’t test this at the time. I’ll try to debug it when I get a chance.

**Comment by davidjoshuaford** [comment]
All good, thanks! :)

**Comment by josephdadams** [comment]
It's because of this silly mistake on my part: https://github.com/bitfocus/companion-module-canon-ptz/blob/aedb29a12fcb9a45a673a6a99d5ac46dec865a46/src/actions.js#L174

**Comment by josephdadams** [comment]
Fixed, tagged, and released into core

**Comment by davidjoshuaford** [comment]
Thanks Joseph - will that be in the 3809 Mac arm build? Seems the latest build is for linux/win. 

The last preset feedback is working well. I reduced the camera polling number from 5000 down to 500 to speed up the change. 

Having trouble getting consistent preview tally lamps. Program on/off works consistently with the module settings. I've built a trigger to change the tally lamp to green when the PTZ's input is selected on the ATEM's Preview. The camera's green preview tally lamp turns on when pushed to Preview, and goes red when cut to Program. But... when cutting back, the lamp turns off altogether. Plus, in layering up feedback states on a button to show either preview or program, the preview feedback often remains on, even when it should be off. All this to say, is it possible to add a Preview tally function into the module configurations (like you have with the "Enable Tally On - Set camera tally ON when the instance variable equals the value" section). I think where I'm getting stuck is that setting turns the global tally ON/OFF, but the tally actions and feedback target specific program/preview tally lamp states. 

Just a thought, hope that's not too convoluted! (The benefit here is a cam assistant would be able to chase the preview tally lamp to select or fine tune PTZ angles before they are cut live). Thanks for your work!

**Comment by davidjoshuaford** [comment]
One more thing that may be a bug unless I'm mistaken – the Recall Preset Mode for Speed doesn't appear to work. Seems like it does work for "Time" and for "Normal", but not for "Speed".

**Comment by josephdadams** [comment]
Ok, I added the tally preview listener just like pgm listener. Please test and open a new issue if it is not working as expected. Please also file a new issue for the ptz speed recall problem so we can try to track that as well. Not sure I can fix it, but please describe steps and actions using.

**Comment by davidjoshuaford** [comment]
You are amazing, thanks Joseph!
