### ISSUE TITLE
Preset Speed Recall

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-canon-ptz#6]
The Recall Preset Mode for "Speed" doesn't appear to work. Seems like it does work for "Time" and for "Normal", but not for "Speed". I've tested changing the Speed parameters at 100 and at 50, but there's no change in speed.

**Comment by josephdadams** [comment]
It's working well here. I did it through the Presets buttons. Did you use the presets or create them manually? It shouldn't matter - just trying to troubleshoot here. I am using a 300.

**Comment by davidjoshuaford** [comment]
I have a 300 also. On further testing, perhaps it's the exponential increase of the Speed parameters with in Canon's camera itself. For instance, I was using a setting of 100 as fast, and 50 as slow...but it was all just fast. However, it appears that 1 is slow, 2 is moderate, 3 quick, and anything 4+ is just plain fast! What speed settings are you using to differentiate between fast/slow?

**Comment by josephdadams** [comment]
I was using 1-2 as "slow" and 45+ to move faster. So yeah - I guess that's it.

**Comment by davidjoshuaford** [comment]
Makes sense. Maybe it's more that Canon would need to implement a linear response rather than exponential. Feels very all or nothing with the way that scale responds. Knowing that 1 is slow is fine for the implementation. Cheers
