### ISSUE TITLE
Thank you and a few requests (PTZ Only / Preset name variable)

### ISSUE THREAD

**Issue by LYMPIA** [bitfocus/companion-module-canon-ptz#8]
Hello,
We've been trying this new module. So far, so good. We'll try it out extensively next week on our live shows.

Dare I ask a couple of requests... ?
Could it be possible to add a "PTZ Only" option on the "Save Preset" preset ? This option is available through the Canon PTZ dedicated web interface and it's really useful as it only saves the Pan Tilt and Zoom informations and not all the other parameters (such as exposure, white balance, focus...). As we're shooting multiple TV set interviews or conferences, it would be very useful to have those fast presets be saved via Companion (instead of the web interface).

And... if I may... Could it be possible to retrieve the preset name through a variable ? On the Canon PTZ Web Interface, one can save a preset and name it. On the very same list we can also read presets names entered through the module you developed. It would be nice to have a variable that can retrieve the preset name and be able to display it on the proper recall preset button. 

Again, thank you very much for your work !

**Comment by josephdadams** [comment]
I added these for you. Pay it forward :)

**Comment by LYMPIA** [comment]
Nice 👍 Thank you very much !
