### ISSUE TITLE
Numeral Feedback for Drive Speed and Drive Time

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-canon-ptz#9]
A minor request - 

Could the feedback data for the Drive Speed and Drive Time be changed to only include the numerals? 

i.e. at the moment the read out is "2 Sec" or "Speed 100". 

Instead if it were only "2" or "100" respectively, that would enable more customizable control on the buttons themselves. (ie the buttons could be customized to read "TIME\n$(ptz1:presetTimeValue)" or "SPEED\n$(ptz1:presetSpeedValue)" to read out as: 

TIME
2

SPEED
100

Thank you!

**Comment by josephdadams** [comment]
Done. Pushed to betas.
